### ISSUE TITLE
CronJob with timeZone param resulting in Deprecation warning

### ISSUE THREAD

**Issue by SMerdzhanov** [kelektiv/node-cron#269]
Hi,

I'm having a non-critical warning which I want to clear from my project. My question is - is it possible to get around this issue and what can I do to resolve it?

Some basic info:

- `node 0.10.40`
- `cron 1.1.0`
- `moment 2.8.1`
- `moment-timezone 0.2.1`

Some implementation details:

- `cronTime = 0 0 12 * * 0`
- Code:

```
new CronJob(cronTime, function() {
            // run some code
        }, null, true, 'America/New_York');
```

This code results in:

```
Deprecation warning: moment().zone is deprecated, use moment().utcOffset instead. https://github.com/moment/moment/issues/1779
Error
    at Moment.zone (/home/stuci/Workspace/MERGE/AlephBetaNode/node_modules/moment/moment.js:746:36)
    at Function.moment.updateOffset (/home/stuci/Workspace/MERGE/AlephBetaNode/node_modules/moment-timezone/moment-timezone.js:352:8)
    at Moment.fn.tz (/home/stuci/Workspace/MERGE/AlephBetaNode/node_modules/moment-timezone/moment-timezone.js:360:12)
    at Object.CronTime.sendAt (/home/stuci/Workspace/MERGE/AlephBetaNode/node_modules/cron/lib/cron.js:101:16)
    at Object.CronTime.getTimeout (/home/stuci/Workspace/MERGE/AlephBetaNode/node_modules/cron/lib/cron.js:126:28)
    at CronJob.start (/home/stuci/Workspace/MERGE/AlephBetaNode/node_modules/cron/lib/cron.js:401:30)
    at new CronJob (/home/stuci/Workspace/MERGE/AlephBetaNode/node_modules/cron/lib/cron.js:370:22)
    at Object.priv.setBumpToTheTopTime (/home/stuci/Workspace/MERGE/AlephBetaNode/app/_models/website_automation/cronJob.js:40:21)
    at /home/stuci/Workspace/MERGE/AlephBetaNode/app/_models/website_automation/cronJob.js:32:26
    at arrayEach (/home/stuci/Workspace/MERGE/AlephBetaNode/node_modules/bookshelf/node_modules/lodash/lodash.js:530:11)
    at Function.forEach (/home/stuci/Workspace/MERGE/AlephBetaNode/node_modules/bookshelf/node_modules/lodash/lodash.js:9319:14)
    at CollectionBase.(anonymous function) [as forEach] (/home/stuci/Workspace/MERGE/AlephBetaNode/node_modules/bookshelf/lib/base/collection.js:755:37)
    at null.<anonymous> (/home/stuci/Workspace/MERGE/AlephBetaNode/app/_models/website_automation/cronJob.js:30:22)
    at tryCatcher (/home/stuci/Workspace/MERGE/AlephBetaNode/node_modules/bookshelf/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/stuci/Workspace/MERGE/AlephBetaNode/node_modules/bookshelf/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/stuci/Workspace/MERGE/AlephBetaNode/node_modules/bookshelf/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/stuci/Workspace/MERGE/AlephBetaNode/node_modules/bookshelf/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/stuci/Workspace/MERGE/AlephBetaNode/node_modules/bookshelf/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/home/stuci/Workspace/MERGE/AlephBetaNode/node_modules/bookshelf/node_modules/bluebird/js/release/promise.js:636:18)
    at Promise._resolveCallback (/home/stuci/Workspace/MERGE/AlephBetaNode/node_modules/bookshelf/node_modules/bluebird/js/release/promise.js:431:57)
    at Promise._settlePromiseFromHandler (/home/stuci/Workspace/MERGE/AlephBetaNode/node_modules/bookshelf/node_modules/bluebird/js/release/promise.js:522:17)
    at Promise._settlePromise (/home/stuci/Workspace/MERGE/AlephBetaNode/node_modules/bookshelf/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/stuci/Workspace/MERGE/AlephBetaNode/node_modules/bookshelf/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/stuci/Workspace/MERGE/AlephBetaNode/node_modules/bookshelf/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/home/stuci/Workspace/MERGE/AlephBetaNode/node_modules/bookshelf/node_modules/bluebird/js/release/promise.js:636:18)
    at Promise._settlePromise (/home/stuci/Workspace/MERGE/AlephBetaNode/node_modules/bookshelf/node_modules/bluebird/js/release/promise.js:580:21)
    at Promise._settlePromise0 (/home/stuci/Workspace/MERGE/AlephBetaNode/node_modules/bookshelf/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/stuci/Workspace/MERGE/AlephBetaNode/node_modules/bookshelf/node_modules/bluebird/js/release/promise.js:691:18)
```

--

I understand that this is more or less related with `moment`, but again it's being used by the package, so I'm not even sure whether or how I can clear that warning. I'm available for any comments or questions!

Thank you for the effort :slightly_smiling_face:

**Comment by ncb000gt** [comment]
Upgrade your `moment-timezone` version. I've listed `^0.5.x` as a dependency for this module in the latest version.

Also, you may want to use 1.2.1 of the `node-cron` module as it is the latest with some bug fixes and such. Let me know if that works. Thanks!

**Comment by SMerdzhanov** [comment]
Hey,

Thank you for the response! I can't test it out at the moment, but definitely would.

I guess that this issue can be closed and considered as fixed given the _upgrade_ mentioned in your comment.
