### ISSUE TITLE
Unhandled rejection Error: Unknown alias: s

### ISSUE THREAD

**Issue by knoxcard** [kelektiv/node-cron#330]
I just started getting this error today out of the blue.  Maybe I changed something, _if I figure it out, I will update this thread._

Unhandled rejection Error: Unknown alias: s
    at C:\indospace.io\services\node_modules\cron\lib\cron.js:302:10
    at String.replace (<anonymous>)
    at CronTime._parse (C:\indospace.io\services\node_modules\cron\lib\cron.js:295:24)
    at new CronTime (C:\indospace.io\services\node_modules\cron\lib\cron.js:37:8)
    at new CronJob (C:\indospace.io\services\node_modules\cron\lib\cron.js:395:18)
    at require.waterfall (C:\indospace.io\services\menu_service.js:35:3)
    at C:\indospace.io\services\node_modules\async\dist\async.js:473:16
    at next (C:\indospace.io\services\node_modules\async\dist\async.js:5315:29)
    at C:\indospace.io\services\node_modules\async\dist\async.js:958:16
    at require.load_models.db (C:\indospace.io\services\menu_service.js:23:7)
    at sequelize.sync.then (C:\indospace.io\services\models\index.js:41:20)
    at tryCatcher (C:\indospace.io\services\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\indospace.io\services\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\indospace.io\services\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\indospace.io\services\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\indospace.io\services\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\indospace.io\services\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\indospace.io\services\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\indospace.io\services\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:756:18)
    at tryOnImmediate (timers.js:717:5)
    at processImmediate [as _immediateCallback] (timers.js:697:5)

**Comment by knoxcard** [comment]
All my fault, had thrown a random s character in one of my source files that initiates node-cron.
