### ISSUE TITLE
unable to start or stop cron after stored it into array

### ISSUE THREAD

**Issue by Mohamed-Abubucker** [kelektiv/node-cron#351]
i am trying to store the crons into an array, and then trying to modify the crons using array index. i can retive cron from the array and can set cronTime too.when i try to do `.start()` or `.stop()` the cron, i am getting the below error while. please help me to resolve this.

 ```
  TypeError: this.cronTime.getTimeout is not a function
        at CronJob.start (/home/bucker/sourceCode/tmmmt-nodesocket/node_modules/cron/lib/cron.js:435:30)
        at _modifyCampaignCron (/home/bucker/sourceCode/tmmmt-nodesocket/server/logics/campaign.js:767:24)
        at campaigns.forEach (/home/bucker/sourceCode/tmmmt-nodesocket/server/logics/campaign.js:798:21)
        at Array.forEach (<anonymous>)
        at Object.initCampaignCrons (/home/bucker/sourceCode/tmmmt-nodesocket/server/logics/campaign.js:790:13)
        at process._tickCallback (internal/process/next_tick.js:68:7)

```

**Comment by ncb000gt** [comment]
It seems like you might be on an older version of the module as the line number in the exception doesn't match up with what is in master.

Also, can you supply some example code and the node/npm/cron versions please? Thanks!

**Comment by Mohamed-Abubucker** [comment]
@ncb000gt , thanks for you reply in this. i changed my code by .map instead of .foreach, now i am getting `this` context with cron object and i can do the stuffs.

thanks!
