### ISSUE TITLE
cron reached maximum iterations

### ISSUE THREAD

**Issue by rguiliani** [kelektiv/node-cron#393]
Time Zone: "" - Cron String: 0 0 19 * * 0 - UTC offset: -07:00 - current Date: Thu Dec 06 2018 13:24:19 GMT-0700

using moment-timezone@0.5.23 and cron@1.5.1

**Comment by ncb000gt** [comment]
So, I tried this locally and got back 5 dates as expected. Here's the code and what I got back. Can you share more about the code?

Code:
```
const CronTime = require('../lib/cron.js').CronTime;

const time = new CronTime('0 0 19 * * 0', null, -7);

console.log(time.sendAt(5));
````

Results:
```
[ moment.parseZone("2018-12-09T19:00:00.000-07:00"),
  moment.parseZone("2018-12-16T19:00:00.000-07:00"),
  moment.parseZone("2018-12-23T19:00:00.000-07:00"),
  moment.parseZone("2018-12-30T19:00:00.000-07:00"),
  moment.parseZone("2019-01-06T19:00:00.000-07:00") ]
```

However, in the linked ticket, I'm seeing the issue described here (and there, with the syntax specified over there).

Syntax:
```
const time = new CronTime('0 0 6 29 11 6', null, 1);
```

Results:
```
node next_at_exception.js
/Users/nick/Code/node-cron/lib/cron.js:240
					throw new Error(
					^
Error: Something went wrong. cron reached maximum iterations.
Please open an  issue (https://github.com/kelektiv/node-cron/issues/new) and provide the following string
Time Zone: "" - Cron String: 0 0 6 29 11 6 - UTC offset: +01:00 - current Date: Sun Dec 09 2018 14:46:07 GMT-0500
    at CronTime._getNextDateFrom (/Users/nick/Code/node-cron/lib/cron.js:240:12)
    at CronTime.sendAt (/Users/nick/Code/node-cron/lib/cron.js:163:18)
    at Object.<anonymous> (/Users/nick/Code/node-cron/examples/next_at_exception.js:4:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
```

Either way, I'm looking into this.

**Comment by ncb000gt** [comment]
@rguiliani and @13pass I took a look at the code and changed it to use a timeout rather than an arbitrary number of iterations of the for loop. Hopefully this alleviates your issue. Give it a try and let me know. Thanks.
