### ISSUE TITLE
Error: Something went wrong. cron reached maximum iterations.

### ISSUE THREAD

**Issue by MilyaushaShigapova** [kelektiv/node-cron#469]
what is the problem what happened?

/home/app/node_modules/cron/lib/cron.js:235

					throw new Error(

					^

Error: Something went wrong. cron reached maximum iterations.

Time Zone: "" - Cron String: 0 * * * * * - UTC offset: +00:00 - current Date: Wed Feb 19 2020 14:07:09 GMT+0000

    at CronTime._getNextDateFrom (/home/app/node_modules/cron/lib/cron.js:235:12)

    at CronTime.sendAt (/home/app/node_modules/cron/lib/cron.js:156:17)

    at CronTime.getTimeout (/home/app/node_modules/cron/lib/cron.js:175:29)

    at CronJob.start (/home/app/node_modules/cron/lib/cron.js:613:31)

    at Timeout.callbackWrapper [as _onTimeout] (/home/app/node_modules/cron/lib/cron.js:665:29)

    at listOnTimeout (timers.js:324:15)

    at processTimers (timers.js:268:5)

**Comment by ncb000gt** [comment]
Can you share some code to help debug?

**Comment by mryellow** [comment]
https://github.com/kelektiv/node-cron/issues/408

**Comment by mikelam14** [comment]
I realized the error would show whenever my CPU utilization is too high (>9x%). That might cause some delay of code and affect something.

**Comment by ncb000gt** [comment]
I pushed up a PR with some changes to allow a "soft warning". Can you please test and report back?

**Comment by intcreator** [comment]
closing in favor of #467
