### ISSUE TITLE
Error: cron reached maximum iterations

### ISSUE THREAD

**Issue by DaniilVysotskiy** [kelektiv/node-cron#484]
On the project `"cron": "1.7.2"` is used.

Since last update, we started getting the error below:
```
Time Zone: "" - Cron String: 0,5,10,15,20,25,30,35,40,45,50,55 * * * * * - UTC offset: +00:00 - current Date: Fri Apr 10 2020 12:33:21 GMT+0000
    at CronTime._getNextDateFrom (/opt/cloud-candy-gaz/node_modules/cron/lib/cron.js:235:12)
    at CronTime.sendAt (/opt/cloud-candy-gaz/node_modules/cron/lib/cron.js:156:17)
    at CronTime.getTimeout (/opt/cloud-candy-gaz/node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (/opt/cloud-candy-gaz/node_modules/cron/lib/cron.js:613:31)
    at Timeout.callbackWrapper [as _onTimeout] (/opt/cloud-candy-gaz/node_modules/cron/lib/cron.js:665:29)
```

It occures usually only on 2-3d day of server uptime, which is wierd. What could go wrong in this case?

**Comment by DaniilVysotskiy** [comment]
Duplicate #478
