### ISSUE TITLE
Error: Something went wrong. cron reached maximum iterations.

### ISSUE THREAD

**Issue by fredkilbourn** [kelektiv/node-cron#517]
```
Error: Something went wrong. cron reached maximum iterations.
                                                Please open an  issue (https://github.com/kelektiv/node-cron/issues/new) and provide the following string
                                                Time Zone: "" - Cron String: 0 * * * * * - UTC offset: -05:00 - current Date: Sat Aug 08 2020 19:48:12 GMT-0500
    at CronTime._getNextDateFrom (/root/vbot/node_modules/cron/lib/cron.js:235:12)
    at CronTime.sendAt (/root/vbot/node_modules/cron/lib/cron.js:156:17)
    at CronTime.getTimeout (/root/vbot/node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (/root/vbot/node_modules/cron/lib/cron.js:613:31)
    at Timeout.callbackWrapper [as _onTimeout] (/root/vbot/node_modules/cron/lib/cron.js:665:29)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

**Comment by eeroan** [comment]
Had exactly the same error

**Comment by stasionok** [comment]
Got that errror today,

**Comment by lautaroramos** [comment]
#478

**Comment by suruaku** [comment]
#522

**Comment by intcreator** [comment]
closing in favor of #467
