### ISSUE TITLE
Error: Something went wrong. cron reached maximum iterations.

### ISSUE THREAD

**Issue by educob** [kelektiv/node-cron#524]
I got this error:

```
Please open an  issue (https://github.com/kelektiv/node-cron/issues/new) and provide the following string
						Time Zone: "" - Cron String: 0 0,3,6,9,12,15,18,21,24,27,30,33,36,39,42,45,48,51,54,57 * * * * - UTC offset: +01:00 - current Date: Fri Sep 04 2020 11:51:45 GMT+0100
    at CronTime._getNextDateFrom (/home/user/graphql/node_modules/cron/lib/cron.js:235:12)
    at CronTime.sendAt (/home/user/graphql/node_modules/cron/lib/cron.js:156:17)
    at CronTime.getTimeout (/home/user/graphql/node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (/home/user/graphql/node_modules/cron/lib/cron.js:613:31)
    at Timeout.callbackWrapper [as _onTimeout] (/home/user/graphql/node_modules/cron/lib/cron.js:665:29)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```
I have 3 jobs defined:

```
new CronJob('*/10 * * * * *', blockchain_job) // I stop this as soon as it starts
new CronJob('0 0 1 * * *', daily_job)
 new CronJob('0 */3 * * * *', fees_fiat_job)
```
I realized that having a cron for blockchain_job, that it's stopped as soon as it starts, doesn't seem to make any sense so I just removed it.

**Comment by intcreator** [comment]
closing in favor of #467
