### ISSUE TITLE
Error: Something went wrong. cron reached maximum iterations.

### ISSUE THREAD

**Issue by go-ananay-nag** [kelektiv/node-cron#527]
Time Zone: "" - Cron String: 0 0 6,12,18 * * * - UTC offset: +05:30 - current Date: Tue Sep 08 2020 06:00:15 GMT+0530

at CronTime._getNextDateFrom (/root/repos/shopnow-micro-service/node_modules/cron/lib/cron.js:235:12)
    at CronTime.sendAt (/root/repos/shopnow-micro-service/node_modules/cron/lib/cron.js:156:17)
    at CronTime.getTimeout (/root/repos/shopnow-micro-service/node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (/root/repos/shopnow-micro-service/node_modules/cron/lib/cron.js:613:31)
    at Timeout.callbackWrapper [as _onTimeout] (/root/repos/shopnow-micro-service/node_modules/cron/lib/cron.js:665:29)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)

**Comment by kasir-barati** [comment]
@go-ananay-nag Can you share a simple repo that can/potentially can reproduce bug again

**Comment by intcreator** [comment]
closing in favor of #467
