### ISSUE TITLE
Error: Something went wrong. cron reached maximum iterations.

### ISSUE THREAD

**Issue by on21life** [kelektiv/node-cron#534]
``
Please open an  issue (https://github.com/kelektiv/node-cron/issues/new) and provide the following string
                                                Time Zone: "" - Cron String: 0 * * * * * - UTC offset: +09:00 - current Date: Wed Oct 21 2020 08:40:39 GMT+0900
``

err stack trace:
``
    at CronTime._getNextDateFrom (/MYPATH1/MYPATH2/MYPATH3/node_modules/cron/lib/cron.js:235:12)
    at CronTime.sendAt (/MYPATH1/MYPATH2/MYPATH3/node_modules/cron/lib/cron.js:156:17)
    at CronTime.getTimeout (/MYPATH1/MYPATH2/MYPATH3/node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (/MYPATH1/MYPATH2/MYPATH3/node_modules/cron/lib/cron.js:613:31)
    at Timeout.callbackWrapper [as _onTimeout] (/MYPATH1/MYPATH2/MYPATH3/node_modules/cron/lib/cron.js:665:29)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
``

in my case,
after reboot instance, it was fixed but still potentially dangerous

**Comment by intcreator** [comment]
closing in favor of #467
