### ISSUE TITLE
Something went wrong. cron reached maximum iterations.

### ISSUE THREAD

**Issue by jackbrown9375** [kelektiv/node-cron#541]
Error: Something went wrong. cron reached maximum iterations.
                                                Please open an  issue (https://github.com/kelektiv/node-cron/issues/new) and provide the following string
                                                Time Zone: "" - Cron String: 0 0,10,20,30,40,50 * * * * - UTC offset: -05:00 - current Date: Sun Dec 06 2020 08:00:22 GMT-0500
    at CronTime._getNextDateFrom (project/node_modules/cron/lib/cron.js:235:12)
    at CronTime.sendAt (project/node_modules/cron/lib/cron.js:156:17)
    at CronTime.getTimeout (project/node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (project/node_modules/cron/lib/cron.js:613:31)
    at Timeout.callbackWrapper (project/node_modules/cron/lib/cron.js:665:29)
    at Timeout._onTimeout (project/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31)
    at listOnTimeout (internal/timers.js:531:17)

**Comment by intcreator** [comment]
closing in favor of #467
