### ISSUE TITLE
Error: Something went wrong. cron reached maximum iterations

### ISSUE THREAD

**Issue by kevinfox1** [kelektiv/node-cron#542]
Please open an  issue (https://github.com/kelektiv/node-cron/issues/new) and provide the following string
						Time Zone: "" - Cron String: 0,20,40 * * * * * - UTC offset: +00:00 - current Date: Fri Dec 04 2020 23:31:09 GMT+0000
    at CronTime._getNextDateFrom (/usr/src/app/app-name/node_modules/cron/lib/cron.js:235:12)
    at CronTime.sendAt (/usr/src/app/app-name/node_modules/cron/lib/cron.js:156:17)
    at CronTime.getTimeout (/usr/src/app/app-name/node_modules/cron/lib/cron.js:175:29)

**Comment by intcreator** [comment]
closing in favor of https://github.com/kelektiv/node-cron/issues/467
