### ISSUE TITLE
Error: Something went wrong. cron reached maximum iterations.

### ISSUE THREAD

**Issue by educob** [kelektiv/node-cron#545]
Please open an  issue (https://github.com/kelektiv/node-cron/issues/new) and provide the following string
						Time Zone: "" - Cron String: 0 0,3,6,9,12,15,18,21,24,27,30,33,36,39,42,45,48,51,54,57 * * * * - UTC offset: +00:00 - current Date: Wed Dec 16 2020 20:42:14 GMT+0000

`at CronTime._getNextDateFrom (/home/obiwan/bapp/graphql/node_modules/cron/lib/cron.js:235:12)
    at CronTime.sendAt (/home/obiwan/bapp/graphql/node_modules/cron/lib/cron.js:156:17)
    at CronTime.getTimeout (/home/obiwan/bapp/graphql/node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (/home/obiwan/bapp/graphql/node_modules/cron/lib/cron.js:613:31)
    at Timeout.callbackWrapper [as _onTimeout] (/home/obiwan/bapp/graphql/node_modules/cron/lib/cron.js:665:29)
`

**Comment by intcreator** [comment]
closing in favor of #467
