### ISSUE TITLE
Something went wrong. cron reached maximum iterations.

### ISSUE THREAD

**Issue by access2content** [kelektiv/node-cron#547]
Time Zone: "" - Cron String: 0 0 * * * * - UTC offset: +05:30 - current Date: Thu 
Dec 24 2020 13:11:39 GMT+0530
    at CronTime._getNextDateFrom (C:\Users\PERI_SUPPORT\Documents\Programming\rejolut\earthtile-core\node_modules\cron\lib\cron.js:235:12)
    at CronTime.sendAt (C:\Users\PERI_SUPPORT\Documents\Programming\rejolut\earthtile-core\node_modules\cron\lib\cron.js:156:17)  
    at CronTime.getTimeout (C:\Users\PERI_SUPPORT\Documents\Programming\rejolut\earthtile-core\node_modules\cron\lib\cron.js:175:29)
    at CronJob.start (C:\Users\PERI_SUPPORT\Documents\Programming\rejolut\earthtile-core\node_modules\cron\lib\cron.js:613:31)    
    at Timeout.callbackWrapper [as _onTimeout] (C:\Users\PERI_SUPPORT\Documents\Programming\rejolut\earthtile-core\node_modules\cron\lib\cron.js:665:29)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)

**Comment by intcreator** [comment]
closing in favor of #467
