### ISSUE TITLE
Something went wrong. cron reached maximum iterations.

### ISSUE THREAD

**Issue by xiaoliu-heng** [kelektiv/node-cron#548]
Time Zone: "" - Cron String: 0 * * * * * - UTC offset: +08:00 - current Date: Fri Dec 25 2020 21:19:47 GMT+0800

```sh
Error: Something went wrong. cron reached maximum iterations.
                                                Please open an  issue (https://github.com/kelektiv/node-cron/issues/new) and provide the following string
                                                Time Zone: "" - Cron String: 0 * * * * * - UTC offset: +08:00 - current Date: Fri Dec 25 2020 21:19:47 GMT+0800
    at CronTime._getNextDateFrom (/Users/xiaoliu/workspace/backend/node_modules/cron/lib/cron.js:235:12)
    at CronTime.sendAt (/Users/xiaoliu/workspace/backend/node_modules/cron/lib/cron.js:156:17)
    at CronTime.getTimeout (/Users/xiaoliu/workspace/backend/node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (/Users/xiaoliu/workspace/backend/node_modules/cron/lib/cron.js:613:31)
    at Timeout.callbackWrapper [as _onTimeout] (/Users/xiaoliu/workspace/backend/node_modules/cron/lib/cron.js:665:29)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```

**Comment by MelodicCrypter** [comment]
I'm also experiencing this issue, just today.

**Comment by intcreator** [comment]
closing in favor of #467
