### ISSUE TITLE
Something went wrong. cron reached maximum iterations.

### ISSUE THREAD

**Issue by TwoAbove** [kelektiv/node-cron#555]
```
/usr/app/node_modules/cron/lib/cron.js:235
					throw new Error(
           ^
Error: Something went wrong. cron reached maximum iterations.
						Please open an  issue (https://github.com/kelektiv/node-cron/issues/new) and provide the following string
						Time Zone: "" - Cron String: 0,5,10,15,20,25,30,35,40,45,50,55 * * * * * - UTC offset: -08:00 - current Date: Mon Feb 22 2021 02:51:19 GMT+0000
    at CronTime._getNextDateFrom (/usr/app/node_modules/cron/lib/cron.js:235:12)
    at CronTime.sendAt (/usr/app/node_modules/cron/lib/cron.js:156:17)
    at CronTime.getTimeout (/usr/app/node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (/usr/app/node_modules/cron/lib/cron.js:613:31)
    at Timeout.callbackWrapper [as _onTimeout] (/usr/app/node_modules/cron/lib/cron.js:665:29)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

Where?
Container, `FROM node:14`
Docker version 19.03.8, build afacb8b7f0
docker-compose version 1.25.3, build d4d1b42b
Linux Mantaray 5.8.0-43-generic #49-Ubuntu SMP Fri Feb 5 03:01:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by intcreator** [comment]
closing in favor of #467
