### ISSUE TITLE
Error: "Something went wrong. cron reached maximum iterations"

### ISSUE THREAD

**Issue by Chandu** [kelektiv/node-cron#561]
We have a cron job scheduled via node-cron which would run every 5 minutes.
Today we have noticed the error(with stack trace) mentioned below and it has brought our process down.
```
Mar 23 01:01:55 ip-10-28-152-190 ssar: Error: Something went wrong. cron reached maximum iterations.
Mar 23 01:01:55 ip-10-28-152-190 ssar: Please open an  issue (https://github.com/kelektiv/node-cron/issues/new) and provide the following string
Mar 23 01:01:55 ip-10-28-152-190 ssar: Time Zone: "" - Cron String: 0 0,5,10,15,20,25,30,35,40,45,50,55 * * * * - UTC offset: -05:00 - current Date: Tue Mar 23 2021 01:01:05 GMT-0500
Mar 23 01:01:55 ip-10-28-152-190 ssar: at CronTime._getNextDateFrom (/home/some-app/node_modules/cron/lib/cron.js:235:12)
Mar 23 01:01:55 ip-10-28-152-190 ssar: at CronTime.sendAt (/home/some-app/node_modules/cron/lib/cron.js:156:17)
Mar 23 01:01:55 ip-10-28-152-190 ssar: at CronTime.getTimeout (/home/some-app/node_modules/cron/lib/cron.js:175:29)
Mar 23 01:01:55 ip-10-28-152-190 ssar: at CronJob.start (/home/some-app/node_modules/cron/lib/cron.js:613:31)
Mar 23 01:01:55 ip-10-28-152-190 ssar: at Timeout.callbackWrapper [as _onTimeout] (/home/some-app/node_modules/cron/lib/cron.js:665:29)
Mar 23 01:01:55 ip-10-28-152-190 ssar: at listOnTimeout (internal/timers.js:549:17)
Mar 23 01:01:55 ip-10-28-152-190 ssar: at processTimers (internal/timers.js:492:7)

```

And here is the string that was asked to be shared:

```Time Zone: "" - Cron String: 0 0,5,10,15,20,25,30,35,40,45,50,55 * * * * - UTC offset: -05:00 - current Date: Tue Mar 23 2021 01:01:05 GMT-0500```

**Comment by therightprofile** [comment]
+1

**Comment by danny-p93** [comment]
Here also, it worked all days before as expected. But then we got that error, at first i thought it has something todo with changing of daylight saving but thats one day later.
My string:
Time Zone: "" - Cron String: 0 0 2 * * * - UTC offset: +01:00 - current Date: Sat Mar 27 2021 02:00:00 GMT+0100

**Comment by CharlesAtArisant** [comment]
I also ran into this Exception.

My String:

Time Zone: "" - Cron String: 0 0,5,10,15,20,25,30,35,40,45,50,55 * * * * - UTC offset: -06:00 - current Date: Tue Mar 30 2021 20:41:00 GMT+0000

-----------------------
2021-03-30T20:41:28.283Z error: uncaughtException: Something went wrong. cron reached maximum iterations.
						Please open an  issue (https://github.com/kelektiv/node-cron/issues/new) and provide the following string
						Time Zone: "" - Cron String: 0 0,5,10,15,20,25,30,35,40,45,50,55 * * * * - UTC offset: -06:00 - current Date: Tue Mar 30 2021 20:41:00 GMT+0000
Error: Something went wrong. cron reached maximum iterations.
						Please open an  issue (https://github.com/kelektiv/node-cron/issues/new) and provide the following string
						Time Zone: "" - Cron String: 0 0,5,10,15,20,25,30,35,40,45,50,55 * * * * - UTC offset: -06:00 - current Date: Tue Mar 30 2021 20:41:00 GMT+0000
    at CronTime._getNextDateFrom (/app/node_modules/cron/lib/cron.js:235:12)
    at CronTime.sendAt (/app/node_modules/cron/lib/cron.js:156:17)
    at CronTime.getTimeout (/app/node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (/app/node_modules/cron/lib/cron.js:613:31)
    at Timeout.callbackWrapper [as _onTimeout] (/app/node_modules/cron/lib/cron.js:665:29)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)

**Comment by dpz3579** [comment]
+1 

Same issue with a cron job that runs every 5 minutes.
I've another cron that runs every 2 minutes, but it never throws this kind of error.

OS: RHEL release 8.2 (Ootpa)

Stack Trace

```

Error: Something went wrong. cron reached maximum iterations.
						Please open an  issue (https://github.com/kelektiv/node-cron/issues/new) and provide the following string
						Time Zone: "" - Cron String: 0 0,5,10,15,20,25,30,35,40,45,50,55 * * * * - UTC offset: +00:00 - current Date: Thu Apr 15 2021 16:03:26 GMT+0000
    at CronTime._getNextDateFrom (/home/ec2-user/repos/nodecronjob/node_modules/cron/lib/cron.js:235:12)
    at CronTime.sendAt (/home/ec2-user/repos/nodecronjob/node_modules/cron/lib/cron.js:156:17)
    at CronTime.getTimeout (/home/ec2-user/repos/nodecronjob/node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (/home/ec2-user/repos/nodecronjob/node_modules/cron/lib/cron.js:613:31)
    at Timeout.callbackWrapper [as _onTimeout] (/home/ec2-user/repos/nodecronjob/node_modules/cron/lib/cron.js:665:29)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)

```

**Comment by suntong** [comment]
`Error: Something went wrong. cron reached maximum iterations.`

Please open an  issue (https://github.com/kelektiv/node-cron/issues/new) and provide the following string

```
Time Zone: "" - Cron String: 0 30 16 * * 1,2,3,4,5 - UTC offset: -04:00 - current Date: Thu Apr 15 2021 18:14:19 GMT-0400
    at CronTime._getNextDateFrom (/path/to/node_modules/cron/lib/cron.js:235:12)
    at CronTime.sendAt (/path/to/node_modules/cron/lib/cron.js:156:17)  
    at CronTime.getTimeout (/path/to/node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (/path/to/node_modules/cron/lib/cron.js:613:31)
    at Timeout.callbackWrapper [as _onTimeout] (/path/to/node_modules/cron/lib/cron.js:665:29)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)

$ node -v
v10.20.0

```

**Comment by aschuetz** [comment]
Same Error: 
 Error  Something went wrong. cron reached maximum iterations.
	Time Zone: "" - Cron String: 0 * * * * * - UTC offset: +00:00 - current Date: Fri Apr 16 2021 19:07:42 GMT+0000

error stack:
• cron.js:235 _getNextDateFrom
    node_modules/cron/lib/cron.js:235:12

• cron.js:156 sendAt
    node_modules/cron/lib/cron.js:156:17

• cron.js:175 getTimeout
    node_modules/cron/lib/cron.js:175:29

• cron.js:613 start
    node_modules/cron/lib/cron.js:613:31

• cron.js:665 callbackWrapper
    node_modules/cron/lib/cron.js:665:29

$ node -v
v12.20.1

**Comment by intcreator** [comment]
closing in favor of #467
