### ISSUE TITLE
App Crashes with error

### ISSUE THREAD

**Issue by victorex27** [kelektiv/node-cron#565]
After my application runs for a while, the app crashes with the following error

``` Time Zone: "" - Cron String: 0 58 * * * * - UTC offset: +01:00 - current Date: Mon Apr 26 2021 15:00:00 GMT+0100
    at CronTime._getNextDateFrom (C:\WEB-APPS\meraki\file-app2\node_modules\cron\lib\cron.js:235:12)
    at CronTime.sendAt (C:\WEB-APPS\meraki\file-app2\node_modules\cron\lib\cron.js:156:17)
    at CronTime.getTimeout (C:\WEB-APPS\meraki\file-app2\node_modules\cron\lib\cron.js:175:29)
    at CronJob.start (C:\WEB-APPS\meraki\file-app2\node_modules\cron\lib\cron.js:613:31)
    at Timeout.callbackWrapper [as _onTimeout] (C:\WEB-APPS\meraki\file-app2\node_modules\cron\lib\cron.js:665:29)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

I have seen similar issue but with no solutions. Who can help me out here?

**Comment by intcreator** [comment]
closing in favor of #467. if you're still getting this error, make sure you're using the latest version of node-cron (2.2.0) and that your environment has enough resources
