### ISSUE TITLE
 Error: Something went wrong. cron reached maximum iterations.

### ISSUE THREAD

**Issue by vishant2211** [kelektiv/node-cron#566]
Error: Something went wrong. cron reached maximum iterations.
                                            Please open an  issue (https://github.com/kelektiv/node-cron/issues/new) and provide the following string

```javascript
Time Zone: "" - Cron String: 0 * 9,10,11,12,13,14,15 * * * - UTC offset: +05:30 - current Date: Mon Mar 01 2021 05:40:12 GMT+0000
     at CronTime._getNextDateFrom (/home/ubuntu/zerodhaAPI/node_modules/cron/lib/cron.js:235:12)
     at CronTime.sendAt (/home/ubuntu/zerodhaAPI/node_modules/cron/lib/cron.js:156:17)
     at CronTime.getTimeout (/home/ubuntu/zerodhaAPI/node_modules/cron/lib/cron.js:175:29)
     at CronJob.start (/home/ubuntu/zerodhaAPI/node_modules/cron/lib/cron.js:613:31)
     at Timeout.callbackWrapper [as _onTimeout] (/home/ubuntu/zerodhaAPI/node_modules/cron/lib/cron.js:665:29)
     at ontimeout (timers.js:436:11)
     at tryOnTimeout (timers.js:300:5)
     at listOnTimeout (timers.js:263:5)
     at Timer.processTimers (timers.js:223:10)
```

**Comment by KevinSailly** [comment]
had the same bug : https://github.com/kelektiv/node-cron/issues/567

PS: using pm2 to start node server, is a potential workaround.

**Comment by intcreator** [comment]
closing in favor of #467
