### ISSUE TITLE
Something went wrong. cron reached maximum iterations.

### ISSUE THREAD

**Issue by martinvillar** [kelektiv/node-cron#569]
Please open an  issue (https://github.com/kelektiv/node-cron/issues/new) and provide the following string
21|xm-api  |     Time Zone: "" - Cron String: 0 * * * * * - UTC offset: +00:00 - current Date: Tue Jun 01 2021 14:50:04 GMT+0000
21|xm-api  |     at CronTime._getNextDateFrom (/home/martin/xm-api/node_modules/cron/lib/cron.js:235:12)
21|xm-api  |     at CronTime.sendAt (/home/martin/xm-api/node_modules/cron/lib/cron.js:156:17)
21|xm-api  |     at CronTime.getTimeout (/home/martin/xm-api/node_modules/cron/lib/cron.js:175:29)
21|xm-api  |     at CronJob.start (/home/martin/xm-api/node_modules/cron/lib/cron.js:613:31)
21|xm-api  |     at Timeout.callbackWrapper [as _onTimeout] (/home/martin/xm-api/node_modules/cron/lib/cron.js:665:29)
21|xm-api  |     at listOnTimeout (internal/timers.js:554:17)
21|xm-api  |     at processTimers (internal/timers.js:497:7)

**Comment by suntong** [comment]
same here.

Error: Something went wrong. cron reached maximum iterations.
                                                Please open an  issue (https://github.com/kelektiv/node-cron/issues/new) and provide the following string
                                                Time Zone: "" - Cron String: 0 0 10 * * 1,2,3,4,5 - UTC offset: +08:00 - current Date: Sun Jul 25 2021 23:27:59 GMT-0400

```
    at CronTime._getNextDateFrom (/path/to/nodejs/node_modules/cron/lib/cron.js:235:12)
    at CronTime.sendAt (/path/to/nodejs/node_modules/cron/lib/cron.js:156:17)
    at CronTime.getTimeout (/path/to/nodejs/node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (/path/to/nodejs/node_modules/cron/lib/cron.js:613:31)
    at Timeout.callbackWrapper [as _onTimeout] (/path/to/nodejs/node_modules/cron/lib/cron.js:665:29)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

**Comment by intcreator** [comment]
closing in favor of #467
