### ISSUE TITLE
start log

### ISSUE THREAD

**Issue by moeik** [kelektiv/node-cron#590]
```
root@0cbd1f39717c:/home/nodebb# ./nodebb start

Starting NodeBB
  "./nodebb stop" to stop the NodeBB server
  "./nodebb log" to view server output
  "./nodebb help" for more commands

root@0cbd1f39717c:/home/nodebb# netstat -tunlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.11:45305        0.0.0.0:*               LISTEN      -                   
udp        0      0 127.0.0.11:48193        0.0.0.0:*                           -                   
root@0cbd1f39717c:/home/nodebb# ./nodebb log

Hit Ctrl-C to exit


                                                Please open an  issue (https://github.com/kelektiv/node-cron/issues/new) and provide the following string
                                                Time Zone: "" - Cron String: 0 0 17 * * 0 - UTC offset: +00:00 - current Date: Tue Dec 07 2021 01:05:08 GMT+0000
    at CronTime._getNextDateFrom (/home/nodebb/node_modules/cron/lib/cron.js:235:12)
    at CronTime.sendAt (/home/nodebb/node_modules/cron/lib/cron.js:156:17)
    at CronTime.getTimeout (/home/nodebb/node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (/home/nodebb/node_modules/cron/lib/cron.js:613:31)
    at new CronJob (/home/nodebb/node_modules/cron/lib/cron.js:576:10)
    at startDigestJob (/home/nodebb/src/user/jobs.js:39:16)
    at Object.User.startJobs (/home/nodebb/src/user/jobs.js:27:3)
    at Object.start.start (/home/nodebb/src/start.js:39:22)

```

**Comment by intcreator** [comment]
closing in favor of #467
