### ISSUE TITLE
Javascript crash

### ISSUE THREAD

**Issue by lukaso** [kelektiv/node-cron#592]
Fing app on macOS Monterey crashed with the following:

Uncaught Exception:
Error: Something went wrong. cron reached maximum iterations.
Please open an  issue (https://github.com/kelektiv/node-cron/issues/new) and provide the following string
Time Zone: "" - Cron String: 0 0 9 * * * - UTC offset: +00:00 - current Date: Wed Jan 05 2022 09:24:52 GMT+0000
at CronTime._getNextDateFrom (/Applications/Fing.app/Contents/Resources/app.asar/node_modules/cron/lib/cron.js:235:12)
at CronTime.sendAt (/Applications/Fing.app/Contents/Resources/app.asar/node_modules/cron/lib/cron.js:156:17)
at CronTime.getTimeout (/Applications/Fing.app/Contents/Resources/app.asar/node_modules/cron/lib/cron.js:175:29)
at CronJob.start (/Applications/Fing.app/Contents/Resources/app.asar/node_modules/cron/lib/cron.js:613:31)
at Timeout.callbackWrapper [as _onTimeout] (/Applications/Fing.app/Contents/Resources/app.asar/node_modules/cron/lib/cron.js:665:29)
at listOnTimeout (internal/timers.js:554:17)
at processTimers (internal/timers.js:497:7)

**Comment by intcreator** [comment]
closing in favor of #467
