### ISSUE TITLE
Cloudron keeps restarting periodically and frequently

### ISSUE THREAD

**Issue by braniqvranik** [kelektiv/node-cron#595]
2022-01-25T17:19:38.106Z box:server ==========================================
2022-01-25T17:19:38.112Z box:server            Cloudron 7.0.4  
2022-01-25T17:19:38.112Z box:server ==========================================
2022-01-25T17:19:38.241Z box:settings initCache: pre-load settings
2022-01-25T17:19:38.279Z box:tasks stopAllTasks: stopping all tasks
2022-01-25T17:19:38.280Z box:shell stopTask spawn: /usr/bin/sudo -S /home/yellowtent/box/src/scripts/stoptask.sh all
2022-01-25T17:19:38.333Z box:dockerproxy startDockerProxy: started proxy on port 3003
Cloudron is up and running. Logs are at /home/yellowtent/platformdata/logs/box.log
2022-01-25T17:19:38.387Z box:reverseproxy writeDashboardConfig: writing admin config for somedomain.club
2022-01-25T17:19:38.433Z box:shell reload spawn: /usr/bin/sudo -S /home/yellowtent/box/src/scripts/restartservice.sh nginx
2022-01-25T17:19:40.533Z box:cloudron onActivated: running post activation tasks
2022-01-25T17:19:40.534Z box:platform initializing addon infrastructure
2022-01-25T17:19:40.536Z box:platform platform is uptodate at version 48.20.0
2022-01-25T17:19:40.536Z box:platform onPlatformReady: platform is ready. infra changed: false
2022-01-25T17:19:40.536Z box:apps schedulePendingTasks: scheduling app tasks
2022-01-25T17:19:40.561Z box:cron startJobs: starting cron jobs
2022-01-25T17:19:40.593Z box:cron backupConfigChanged: schedule 00 00 3 * * * (Europe/Prague)
2022-01-25T17:19:40.601Z box:cron autoupdatePatternChanged: pattern - never (Europe/Prague)
2022-01-25T17:19:40.601Z box:cron Dynamic DNS setting changed to false
2022-01-25T17:19:50.472Z box:apphealthmonitor app health: 15 alive / 0 dead.
2022-01-25T17:19:54.927Z box:updatechecker checkBoxUpdates: checking for updates
2022-01-25T17:19:55.648Z box:updatechecker checkBoxUpdates: no updates
2022-01-25T17:19:55.649Z box:updatechecker checkAppUpdates: checking for updates
2022-01-25T17:20:00.064Z box:scheduler sync: adding jobs of 4f2219db-2c05-4eb7-9971-7ff52999cb0d (nextcloud.somedomain.club)
2022-01-25T17:20:00.342Z box:scheduler createJobs: housekeeping (nextcloud.somedomain.club) will run in container 4f2219db-2c05-4eb7-9971-7ff52999cb0d-housekeeping
2022-01-25T17:20:00.351Z box:scheduler sync: adding jobs of 82ad40c2-5723-4c71-b715-58809e1ef7bf (project.somedomain.club)
2022-01-25T17:20:00.479Z box:scheduler createJobs: cronjob (project.somedomain.club) will run in container 82ad40c2-5723-4c71-b715-58809e1ef7bf-cronjob
2022-01-25T17:20:00.483Z box:scheduler sync: adding jobs of a1e990f5-cccb-4fd8-b96e-c7900f7cb8c9 (finance.somedomain.club)
2022-01-25T17:20:00.637Z box:scheduler createJobs: update_feeds (finance.somedomain.club) will run in container a1e990f5-cccb-4fd8-b96e-c7900f7cb8c9-update_feeds
2022-01-25T17:20:00.643Z box:scheduler sync: adding jobs of e5e806af-5831-4b26-91ab-85a6ca9e7cde (share.somedomain.club)
2022-01-25T17:20:00.768Z box:apphealthmonitor app health: 15 alive / 0 dead.
2022-01-25T17:20:00.795Z box:scheduler createJobs: housekeeping (share.somedomain.club) will run in container e5e806af-5831-4b26-91ab-85a6ca9e7cde-housekeeping
2022-01-25T17:21:58.526Z box:reverseproxy writeDefaultConfig: writing configs for endpoint "ip"
2022-01-25T17:21:58.541Z box:shell reload spawn: /usr/bin/sudo -S /home/yellowtent/box/src/scripts/restartservice.sh nginx
2022-01-25T17:21:59.287Z box:apphealthmonitor setHealth: 0cf31480-bd78-4eeb-bdd5-718cc8bb95fb (forum.somedomain.club) waiting for 1080.713 to update health
2022-01-25T17:21:59.775Z box:apphealthmonitor setHealth: 0cf31480-bd78-4eeb-bdd5-718cc8bb95fb (forum.somedomain.club) waiting for 1080.225 to update health
2022-01-25T17:22:00.343Z box:apphealthmonitor app health: 15 alive / 0 dead.
2022-01-25T17:22:00.660Z box:apphealthmonitor setHealth: 0cf31480-bd78-4eeb-bdd5-718cc8bb95fb (forum.somedomain.club) waiting for 1079.34 to update health
2022-01-25T17:22:00.968Z box:apphealthmonitor app health: 15 alive / 0 dead.
2022-01-25T17:22:01.104Z box:apphealthmonitor app health: 15 alive / 0 dead.
2022-01-25T17:22:10.435Z box:apphealthmonitor app health: 15 alive / 0 dead.
2022-01-25T17:22:20.392Z box:apphealthmonitor app health: 15 alive / 0 dead.
2022-01-25T17:22:30.482Z box:apphealthmonitor app health: 15 alive / 0 dead.
Error: Something went wrong. cron reached maximum iterations.
						Please open an  issue (https://github.com/kelektiv/node-cron/issues/new) and provide the following string
						Time Zone: "" - Cron String: 0,10,20,30,40,50 * * * * * - UTC offset: +00:00 - current Date: Tue Jan 25 2022 17:24:13 GMT+0000
    at CronTime._getNextDateFrom (/home/yellowtent/box/node_modules/cron/lib/cron.js:235:12)
    at CronTime.sendAt (/home/yellowtent/box/node_modules/cron/lib/cron.js:156:17)
    at CronTime.getTimeout (/home/yellowtent/box/node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (/home/yellowtent/box/node_modules/cron/lib/cron.js:613:31)
    at Timeout.callbackWrapper [as _onTimeout] (/home/yellowtent/box/node_modules/cron/lib/cron.js:665:29)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)

**Comment by intcreator** [comment]
closing in favor of #467
