### ISSUE TITLE
Error: Something went wrong. cron reached maximum iterations.

### ISSUE THREAD

**Issue by kingjaehyuk** [kelektiv/node-cron#599]
### Description
```
Error: Something went wrong. cron reached maximum iterations.
						Please open an  issue (https://github.com/kelektiv/node-cron/issues/new) and provide the following string
						Time Zone: "" - Cron String: 0 0,30 * * * * - UTC offset: +09:00 - current Date: Wed Feb 16 2022 04:00:11 GMT+0000
    at CronTime._getNextDateFrom (/home/ec2-user/server/fw/trunk/fw_jh/dist.fw/node_modules/cron/lib/cron.js:235:12)
    at CronTime.sendAt (/home/ec2-user/server/fw/trunk/fw_jh/dist.fw/node_modules/cron/lib/cron.js:156:17)
    at CronTime.getTimeout (/home/ec2-user/server/fw/trunk/fw_jh/dist.fw/node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (/home/ec2-user/server/fw/trunk/fw_jh/dist.fw/node_modules/cron/lib/cron.js:613:31)
    at Timeout.callbackWrapper [as _onTimeout] (/home/ec2-user/server/fw/trunk/fw_jh/dist.fw/node_modules/cron/lib/cron.js:665:29)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
```

### Additional information
```
version: "cron": "^1.8.2"
```

**Comment by amrelshinawy1** [comment]
this happened with me too any new updates

**Comment by carlo23666** [comment]
This lib has a loop protection, when collecting the data takes more than 5 seconds then cronjs will throw that error

**Comment by intcreator** [comment]
closing in favor of #467
