### ISSUE TITLE
A JavaScript error occurred in the main process - Uncaught Exception: Error: Something went wrong. cron reached maximum iterations.

### ISSUE THREAD

**Issue by edfrutos** [kelektiv/node-cron#601]
Time Zone: "" - Cron String: 0 0 9 * * * - UTC offset: +01:00 - current Date: Tue Mar 01 2022 09:00:10 GMT+0100
at CronTime._getNextDateFrom (/Applications/Fing.app/Contents/Resources/app.asar/node_modules/cron/lib/cron.js:235:12)
at CronTime.sendAt (/Applications/Fing.app/Contents/Resources/app.asar/node_modules/cron/lib/cron.js:156:17)
at CronTime.getTimeout (/Applications/Fing.app/Contents/Resources/app.asar/node_modules/cron/lib/cron.js:175:29)
at CronJob.start (/Applications/Fing.app/Contents/Resources/app.asar/node_modules/cron/lib/cron.js:613:31)
at Timeout.callbackWrapper [as _onTimeout] (/Applications/Fing.app/Contents/Resources/app.asar/node_modules/cron/lib/cron.js:665:29)
at listOnTimeout (internal/timers.js:554:17)
at processTimers (internal/timers.js:497:7)

**Comment by carlo23666** [comment]
https://github.com/kelektiv/node-cron/issues/599#issuecomment-1057806566

**Comment by dikiamust** [comment]
I have the same issue, and still can't find the answer
