### ISSUE TITLE
Time Zone: "" - Cron String: 0 * * * * * - UTC offset: -03:00 - current Date: Thu Mar 03 2022 09:38:10 GMT-0300

### ISSUE THREAD

**Issue by NayFreire** [kelektiv/node-cron#602]
Error: Something went wrong. cron reached maximum iterations.
    at CronTime._getNextDateFrom (node_modules/cron/lib/cron.js:235:12)
    at CronTime.sendAt (node_modules/cron/lib/cron.js:156:17)
    at CronTime.getTimeout (node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (node_modules/cron/lib/cron.js:613:31)
    at Timeout.callbackWrapper [as _onTimeout] (node_modules/cron/lib/cron.js:665:29)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)

I'm not sure, but maybe this issue was caused by lack of memory. When this error ocurred, my memory was at 99%. I restarted my app, and it's running as usual

**Comment by intcreator** [comment]
closing in favor of #467
