### ISSUE TITLE
Error: Something went wrong. cron reached maximum iterations.

### ISSUE THREAD

**Issue by kennycharles** [kelektiv/node-cron#608]
Full ERROR:

Error: Something went wrong. cron reached maximum iterations.
						Please open an  issue (https://github.com/kelektiv/node-cron/issues/new) and provide the following string
						Time Zone: "" - Cron String: 0 0,10,20,30,40,50 * * * * - UTC offset: -04:00 - current Date: Mon Apr 25 2022 16:20:13 GMT+0000
    at CronTime._getNextDateFrom (/root/apps/adew/node_modules/cron/lib/cron.js:235:12)
    at CronTime.sendAt (/root/apps/adew/node_modules/cron/lib/cron.js:156:17)
    at CronTime.getTimeout (/root/apps/adew/node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (/root/apps/adew/node_modules/cron/lib/cron.js:613:31)
    at Timeout.callbackWrapper [as _onTimeout] (/root/apps/adew/node_modules/cron/lib/cron.js:665:29)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)

**Comment by AbdelrahmanHafez** [comment]
Hello @kennycharles 
I actually recently found out about how simple this is.

You simply pass a date object in the future instead of the expression.
```js
const { CronJob } = require('cron');
const job = new CronJob(
	new Date('2022-05-10T20:55:53.182Z'),
	function() {
		console.log('You will see this message exactly at that date');
	}
);

job.start();
```

**Comment by intcreator** [comment]
please close this issue and refer to the canonical issue at #467. if you get an error message telling you to open a new issue it's because you're using an old version of node-cron
