### ISSUE TITLE
cron reached maximum iterations

### ISSUE THREAD

**Issue by Arlen22** [kelektiv/node-cron#616]
```
Time Zone: "" - Cron String: 0 30 * * * * - UTC offset: +00:00 - current Date: Sat May 14 2022 03:30:17 GMT+0000
```

```
2022-05-14T03:30:27: PM2 log: --- PM2 global error caught ---------------------------------------------------
2022-05-14T03:30:29: PM2 log: Time                 : Sat May 14 2022 03:30:28 GMT+0000 (Coordinated Universal Time)
2022-05-14T03:30:30: PM2 error: Something went wrong. cron reached maximum iterations.
                                                Please open an  issue (https://github.com/kelektiv/node-cron/issues/new) and provide the following string
                                                Time Zone: "" - Cron String: 0 30 * * * * - UTC offset: +00:00 - current Date: Sat May 14 2022 03:30:17 GMT+0000
2022-05-14T03:30:33: PM2 error: Error: Something went wrong. cron reached maximum iterations.
                                                Please open an  issue (https://github.com/kelektiv/node-cron/issues/new) and provide the following string
                                                Time Zone: "" - Cron String: 0 30 * * * * - UTC offset: +00:00 - current Date: Sat May 14 2022 03:30:17 GMT+0000
    at CronTime._getNextDateFrom (/usr/lib/node_modules/pm2/node_modules/cron/lib/cron.js:235:12)
    at CronTime.sendAt (/usr/lib/node_modules/pm2/node_modules/cron/lib/cron.js:156:17)
    at CronTime.getTimeout (/usr/lib/node_modules/pm2/node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (/usr/lib/node_modules/pm2/node_modules/cron/lib/cron.js:613:31)
    at Timeout.callbackWrapper [as _onTimeout] (/usr/lib/node_modules/pm2/node_modules/cron/lib/cron.js:665:29)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
2022-05-14T03:30:34: PM2 log: ===============================================================================
2022-05-14T03:30:35: PM2 error: [PM2] Resurrecting PM2
internal/child_process.js:408
    throw errnoException(err, 'spawn');
    ^

Error: spawn ENOMEM
    at ChildProcess.spawn (internal/child_process.js:408:11)
    at Object.spawn (child_process.js:553:9)
    at Domain.<anonymous> (/usr/lib/node_modules/pm2/lib/Daemon.js:49:49)
    at Object.onceWrapper (events.js:421:26)
    at Domain.emit (events.js:314:20)
    at Domain.EventEmitter.emit (domain.js:483:12)
    at Domain._errorHandler (domain.js:247:23)
    at Object.<anonymous> (domain.js:157:29)
    at process._fatalException (internal/process/execution.js:164:29) {
  errno: 'ENOMEM',
  code: 'ENOMEM',
  syscall: 'spawn'
}
```

**Comment by BertBR** [comment]
There's any solution? I have same problem.

**Comment by intcreator** [comment]
my PR didn't fix the bug that causes the failsafe to activate, it just tries to stop people from opening tons of new issues that likely all have to do with the same underlying bug. that being said, @Arlen22 please close this issue and refer to the canonical issue at #467. if you get an error message telling you to open a new issue it's because you're using an old version of node-cron
