### ISSUE TITLE
TypeError: Cannot read property '_isAMomentObject' of undefined

### ISSUE THREAD

**Issue by appjitsu** [kelektiv/node-cron#618]
### Description

/home/appuser/node_modules/cron/lib/cron.js:42
		if (this.source instanceof Date || this.source._isAMomentObject) {
		                                               ^

TypeError: Cannot read property '_isAMomentObject' of undefined
    at new CronTime (/home/appuser/node_modules/cron/lib/cron.js:42:50)
    at new CronJob (/home/appuser/node_modules/cron/lib/cron.js:565:19)
    at Object.<anonymous> (/home/appuser/index.js:14:26)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47

**Comment by appjitsu** [comment]
user error ;)
