### ISSUE TITLE
Error: Something went wrong. cron reached maximum iterations.

### ISSUE THREAD

**Issue by MarcusGV** [kelektiv/node-cron#619]
Hum im just followin the instruccions in the error :)

Please open an  issue (https://github.com/kelektiv/node-cron/issues/new) and provide the following string
Time Zone: "" - Cron String: 0 22 15 * * 1,2,3,4,5 - UTC offset: -05:00 - current Date: Fri Jun 03 2022 15:22:08 GMT-0500
    at CronTime._getNextDateFrom (C:\Cabezut\Back-Cabezut2\node_modules\cron\lib\cron.js:235:12)
    at CronTime.sendAt (C:\Cabezut\Back-Cabezut2\node_modules\cron\lib\cron.js:156:17)
    at CronTime.getTimeout (C:\Cabezut\Back-Cabezut2\node_modules\cron\lib\cron.js:175:29)
    at CronJob.start (C:\Cabezut\Back-Cabezut2\node_modules\cron\lib\cron.js:613:31)
    at Timeout.callbackWrapper [as _onTimeout] (C:\Cabezut\Back-Cabezut2\node_modules\cron\lib\cron.js:665:29)

**Comment by intcreator** [comment]
closing in favor of #467
