### ISSUE TITLE
Error: Something went wrong. cron reached maximum iterations.

### ISSUE THREAD

**Issue by TomoyoshiToyoda** [kelektiv/node-cron#620]
Hi, I have an error with your product.
As an error message says, your product will be happy if you check the one out.
I'm afraid this issue is already an existing one, like [this](https://github.com/kelektiv/node-cron/issues/619), though.
```
/home/app/app/node_modules/cron/lib/cron.js:235
throw new Error(
^
Error: Something went wrong. cron reached maximum iterations.

Please open an issue (https://github.com/kelektiv/node-cron/issues/new) and provide the following string
Time Zone: "" - Cron String: 6 * * * * * - UTC offset: +09:00 - current Date: Mon Jun 20 2022 07:27:15 GMT+0000
at CronTime._getNextDateFrom (/home/app/app/node_modules/cron/lib/cron.js:235:12)
at CronTime.sendAt (/home/app/app/node_modules/cron/lib/cron.js:156:17)
at CronTime.getTimeout (/home/app/app/node_modules/cron/lib/cron.js:175:29)
at CronJob.start (/home/app/app/node_modules/cron/lib/cron.js:613:31)
at Timeout.callbackWrapper [as _onTimeout] (/home/app/app/node_modules/cron/lib/cron.js:665:29)
at listOnTimeout (internal/timers.js:549:17)
at processTimers (internal/timers.js:492:7)
```

**Comment by michael-azogu** [comment]
how many iterations do you think it took to break

**Comment by TomoyoshiToyoda** [comment]
I guess you're thinking about the probability of recurrence.
It's like below:
- I have had the phenomenon three times ever.
- All three had been seen after 7 or 9 months after starting.
- All three are scheduled ones per minute.

**Comment by intcreator** [comment]
please close this issue and refer to the canonical issue at #467. if you get an error message telling you to open a new issue it's because you're using an old version of node-cron
