### ISSUE TITLE
Something went wrong. cron reached maximum iterations

### ISSUE THREAD

**Issue by idevchew** [kelektiv/node-cron#632]
My service crashed after a few weeks .....

 Time Zone: "" - Cron String: 0 * * * * * - UTC offset: +01:00 - current Date: Tue Nov 01 2022 14:52:17 GMT+0000
    at CronTime._getNextDateFrom (/home/ec2-user/mpc-base/node_modules/cron/lib/cron.js:235:12)
    at CronTime.sendAt (/home/ec2-user/mpc-base/node_modules/cron/lib/cron.js:156:17)
    at CronTime.getTimeout (/home/ec2-user/mpc-base/node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (/home/ec2-user/mpc-base/node_modules/cron/lib/cron.js:613:31)
    at Timeout.callbackWrapper [as _onTimeout] (/home/ec2-user/mpc-base/node_modules/cron/lib/cron.js:665:29)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)

**Comment by intcreator** [comment]
please close this issue and refer to the canonical issue at #467. if you get an error message telling you to open a new issue it's because you're using an old version of node-cron
