### ISSUE TITLE
Error: Something went wrong. cron reached maximum iterations.

### ISSUE THREAD

**Issue by AndresCUd** [kelektiv/node-cron#635]
There is an error with the cron  - /usr/src/app/node_modules/cron/lib/cron.js:235

It throw this error

Time Zone: "" - Cron String: 0,20,40 * * * * * - UTC offset: +00:00 - current Date: Wed Nov 30 2022 19:51:50 GMT+0000
    at CronTime._getNextDateFrom (/usr/src/app/node_modules/cron/lib/cron.js:235:12)
    at CronTime.sendAt (/usr/src/app/node_modules/cron/lib/cron.js:156:17)
    at CronTime.getTimeout (/usr/src/app/node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (/usr/src/app/node_modules/cron/lib/cron.js:613:31)
    at Timeout.callbackWrapper [as _onTimeout] (/usr/src/app/node_modules/cron/lib/cron.js:665:29)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)

**Comment by intcreator** [comment]
please close this issue. there is a canonical issue for this bug at #467
