### ISSUE TITLE
Getting error date.format is not a function

### ISSUE THREAD

**Issue by tbhaxor** [kelektiv/node-cron#636]
### Description

I am getting the following error in the version v2.0.0

https://github.com/kelektiv/node-cron/blob/master/lib/time.js#L271

Cron expression I am using
```js
CronExpression.EVERY_MINUTE
```

### Screenshots

![Screenshot_20221202_082404](https://user-images.githubusercontent.com/28386721/205205019-bd728624-2c4d-47ad-9f39-61db5700687f.png)

**Comment by radcapitalist** [comment]
Same problem here.  I'm at version 2.1.0.  The crash is in this code here:

`				// hard stop if the current date is after the expected execution
				if (Date.now() > timeout) {
					throw new Error(
						`Something went wrong. It took over five seconds to find the next execution time for the cron job.
							Please refer to the canonical issue (https://github.com/kelektiv/node-cron/issues/467) and provide the following string if you would like to help debug:
							Time Zone: ${zone || '""'} - Cron String: ${this} - UTC offset: ${date.format(
							'Z'
						)} - current Date: ${luxon.DateTime.local().toString()}`
					);
				}
`

Curious, @tbhaxor , if this happens every time for you or intermittently.  For me, I'm getting this intermittently when running my unit tests when I ask for a bunch of next dates.  I'll keep investigating.

Eric

**Comment by ChrisTolmeijer** [comment]
Running into this issue too. Programmatically starting a cron with `0 */5 * * * *` as interval.
<img width="945" alt="Screen Shot 2022-12-24 at 3 37 37 PM" src="https://user-images.githubusercontent.com/3226726/209450445-6facc2f6-b9bc-461a-8f26-d59f8de31c17.png">

For me it happens randomly so far. Need to catch this anyhow since it's apparently happening when it's already about to throw an exception. However, maybe the fact that this error is happening generating the error message is indicative of another underlying problem.

**Comment by lk77** [comment]
i have the same issue it seems

```
paul_drink line : 2 source : file:///storage/emulated/0/app/18d69ebda12db328db91.bundle.js TypeError: n.format is not a function
    at l._getNextDateFrom (file:///storage/emulated/0/app/18d69ebda12db328db91.bundle.js:2:258591)
    at l.sendAt (file:///storage/emulated/0/app/18d69ebda12db328db91.bundle.js:2:257749)
    at n.nextDates (file:///storage/emulated/0/app/18d69ebda12db328db91.bundle.js:2:255002)
    at t.startTask (file:///storage/emulated/0/app/18d69ebda12db328db91.bundle.js:2:106681)
    at t.addGlobalTasks (file:///storage/emulated/0/app/18d69ebda12db328db91.bundle.js:2:105620)
    at new t (file:///storage/emulated/0/app/18d69ebda12db328db91.bundle.js:2:105351)
    at t.mounted (file:///storage/emulated/0/app/18d69ebda12db328db91.bundle.js:2:107997)
    at s.e.init (file:///storage/emulated/0/app/18d69ebda12db328db91.bundle.js:2:99153)
    at Sr.<anonymous> (file:///storage/emulated/0/app/18d69ebda12db328db91.bundle.js:2:207994)
    at Array.<anonymous> (file:///storage/emulated/0/app/18d69ebda12db328db91.bundle.js:2:12362),vue-component-5-e,nextTick
```

**Comment by tbhaxor** [comment]
I have now moved on to different package https://www.npmjs.com/package/node-cron, it is working fine for me

**Comment by barisusakli** [comment]
Will there be a 2.2.1 with this fix?

**Comment by intcreator** [comment]
yeah, working on publishing to NPM. might be a 2.3.0 though since we've changed some heavier stuff as well

**Comment by ledlamp** [comment]
@barisusakli wow, my nodebb forum also broken as of 12h ago with this error. i wonder what happened! this code looks strange 🤨 https://github.com/kelektiv/node-cron/blob/03f94ad825009e26f58a63ce6316d811aff76990/lib/time.js#L262-L278

and #630 doesn't solve anything, it's still gonna throw the error ☹️ #408 #467 looks like it's been around for years and nobody knows what's wrong? 😦

**Comment by intcreator** [comment]
@ledlamp #467 is a pretty general error which can have a number of causes. basically any time the CPU lags too much the error can be thrown. this can be due to infinite loops, overloaded systems, etc. honestly we should close that issue and focus on issues that have specific causes. no program is perfect so it's unreasonable to expect that it will absolutely never fail

**Comment by cryptomaxsun** [comment]
https://github.com/dvandal/cryptonote-nodejs-pool/issues/745
I have a similar problem, how can I solve it?

**Comment by ledlamp** [comment]
> @ledlamp #467 is a pretty general error which can have a number of causes. basically any time the CPU lags too much the error can be thrown. this can be due to infinite loops, overloaded systems, etc. honestly we should close that issue and focus on issues that have specific causes. no program is perfect so it's unreasonable to expect that it will absolutely never fail

issue was #638 fixed in #639
