### ISSUE TITLE
"Error: WARNING: Date in past. Will never be fired." crash inside callback wrapper

### ISSUE THREAD

**Issue by Cyberbeni** [kelektiv/node-cron#813]
### Description

I was using 2.2.0 but cross-checking the code with 3.1.6, this issue still exists.

I have a daily schedule to set up triggers for the day:
https://github.com/Cyberbeni/node-red-contrib-cb-suncron/blob/3b3441c95a0fb4ab2356e906c810d3ef0e8de80f/src/SuncronLocation.ts#L29-L34

Setting up the jobs looks like this: https://github.com/Cyberbeni/node-red-contrib-cb-suncron/blob/3b3441c95a0fb4ab2356e906c810d3ef0e8de80f/src/Suncron.ts#L44-L59

I had this crash today (and probably had multiple similar ones in the past as I had some skipped schedules):
```
9 Dec 15:49:24 - [red] Uncaught Exception:
9 Dec 15:49:24 - [error] Error: WARNING: Date in past. Will never be fired.
    at CT.sendAt (/data/node_modules/cron/lib/time.js:177:12)
    at CT.getTimeout (/data/node_modules/cron/lib/time.js:202:29)
    at Timeout.callbackWrapper [as _onTimeout] (/data/node_modules/cron/lib/job.js:141:36)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
```

### Expected Behavior

If diff is more than 0 but newTimeout would be negative (because slow hardware or whatever), we shouldn't throw an error that can't be handled.

### Actual Behavior

Occasional crash with the included call stack.

### Possible Fix

Treat `this.cronTime.getTimeout()` throwing an error as if diff was not more than 0.

### Steps to Reproduce

Insert a 1 second sleep before this line to imitate slow hardware:

https://github.com/kelektiv/node-cron/blob/d6143937d8774d8e4f5dcf3fcb86b296e2811c29/src/job.ts#L235

Then just setup a job with a single Date and an onTick callback.

### Context

see description

### Your Environment

- **`cron` version**: 2.2.0
- **NodeJS version**: nodered/node-red:2c51c6aaed04
- **Operating System and version**: nodered/node-red:2c51c6aaed04
- **TypeScript version (if applicable)**: 4.9.5
- **Link to your project (if applicable)**: https://github.com/Cyberbeni/node-red-contrib-cb-suncron

**Comment by nguyenvyy** [comment]
I face this issue too, with the difference between luxon.DateTime.local() and the date being 1 millisecond.
cron version: 2.3.1
![image](https://github.com/kelektiv/node-cron/assets/39361315/a96d8e5a-93f4-45e3-80c6-5f6279f27e07)

**Comment by sheerlox** [comment]
What would be the best behavior in your opinion?

If your software is running on under-sized hardware / having bottlenecks in the implementation, and the planned execution date is missed, should we try to catch back (i.e. execute the tick ASAP)?

Some use cases might not go well with this, and having this error thrown indicates that to maintain consistency in your schedule, you should either upgrade the hardware you're running on or address potential bottlenecks in your software.

Let's get the discussion going on this, please let us know your thoughts.

**Comment by Cyberbeni** [comment]
My hardware is at 4% CPU usage at all times. From the mdn web docs, I see that the delay passed to setTimeout is a minimum, so if I set a date less than 24 hours away then diff should never be positive, yet it is.

Executing instantly instead of throwing an uncatchable error would be preferred in my case.

**Comment by Cyberbeni** [comment]
Is there a reason why we are calculating diff instead of just checking remaining > 0 in the first place?

**Comment by sheerlox** [comment]
> Is there a reason why we are calculating diff instead of just checking remaining > 0 in the first place?

From https://github.com/kelektiv/node-cron/pull/259:
> This patch prevents onTick() to be called twice if setTimeout callback was called earlier than expected due to time adjustment. It just measures how much time passed since we set timeout and if it's less than it should it reschedules onTick call.

---

> Executing instantly instead of throwing an uncatchable error would be preferred in my case.

A solution I might think of would be to add a new parameter `tolerableDelay` (in ms) defaulting to `0` (no breaking change), which would be used somewhat like this:

```ts
if (this.realDate) { 
  if (DateTime.local() > date) { 
    if (DateTime.local() > date + tolerableDelay) { 
      throw new CronError('WARNING: Date in past. Will never be fired. Try adjusting the tolerableDelay parameter.'); 
    }

    return date + tolerableDelay;
  }

  return date;
}
```

This way you could control how much you want to allow executing jobs that missed the execution date.

Does that sound like an acceptable solution to your issue?

*Implementation note: we would also need to apply that parameter in other places so it applies to regular cron jobs as well.*

**Comment by Cyberbeni** [comment]
In case of `tolerableDelay = Infinity`, that results in `getTimeout` also returning `Infinity`.

It would fix my issue but it wouldn't fix people randomly running into this issue.

If setTimeout fires after the target date then that already allows infinite delays. It's only in the case of the second measurement inside the same runloop run being negative, while the first being positive when a crash happens instead of just a couple millisecond delay. If I understand how JS+this npm package works currently, let's say we set a cron job to trigger every second and the code being executed by the trigger takes 10 seconds then we constantly get 9-10 second delays and a lot of triggers are getting skipped.

So I think executing instantly in this case is still the best option. (And also most consistent with how things currently work)

**Comment by sheerlox** [comment]
> let's say we set a cron job to trigger every second and the code being executed by the trigger takes 10 seconds then we constantly get 9-10 second delays and a lot of triggers are getting skipped.

We recently added an option to wait for callback completion, but the default behavior remains as before: whatever the time it takes for the callback to complete, the callback will be called every second (in your example). However, if the callback is running some expensive thread-blocking operations, this might affect the execution of the scheduling loop, hence calls to `setTimeout`, and might introduce a variable delay in the regular execution of the callback.

**Comment by sheerlox** [comment]
The issue and work we're doing in#805 is actually somewhat related to that issue.

Here's a draft fix I've pushed to see how things behave in production (#805 is actually very hard to reproduce): https://github.com/sheerlox/node-cron/commit/187dbe57ada28217b810b231bf57afdfe3a3b394#diff-a66bffdb979d130e04df61edb944cc04d2fdedf8117ca2732cb6d119d5f5e7b2

**Comment by sheerlox** [comment]
A discussion is happening on https://github.com/kelektiv/node-cron/issues/962 to add a `tolerableDelay` parameter for regular cron jobs (i.e. not providing a specific date, but a cron expression).

I believe we should be able to use the same parameter(s) for both issues.

**Comment by intcreator** [comment]
#980 (released in 4.3.0) provides a workaround for this. does this solve your issue @Cyberbeni?

**Comment by ancasicolica** [comment]
@intcreator : #980 (resp. #962) introduces a threshold value which should, as I understand, solve this problem.

Either I don't understand how this threshold works or there is a bug with this feature:

I created a test file which should fire the job immediately, as it is inside the threshold tolerance:

```
#!/usr/bin/env node
const {DateTime} = require('luxon');
const {CronJob}  = require('cron');

let scheduledTs = DateTime.now().minus({seconds: 1});
try {
  const job =
          CronJob.from({
              cronTime:     scheduledTs.set({ 'milliseconds': 0}),
              onTick:       () => {
                console.log('done');
              },
              start:        true,
              timezone:     'Europe/Berlin',
              errorHandler: err => {
                console.log('err', err)
              },
              runOnInit:    false,
              name:         `event test`,
              threshold:    3000  // 3 seconds tolerance - the job with 1 sec in past should be fired immediately
            }
          );
}
catch (err) {
  console.error('Error while creating CronJob', err);
}
```

[cronTest.js](https://github.com/user-attachments/files/24534309/cronTest.js)

Instead of firing the onTick handler immediately, the application crashes.

I added a debug message in time.js (in sendAt()):

```
 if (this.realDate) {
            if (luxon_1.DateTime.local() > date) {
              console.log('CRON-DEBUG', luxon_1.DateTime.local() , date);
                throw new errors_1.CronError('WARNING: Date in past. Will never be fired.');
            }
            return date;
        }
```
 
What I see on the console:

```
CRON-DEBUG DateTime { ts: 2026-01-09T20:27:53.735+01:00, zone: Europe/Zurich, locale: en-US } DateTime { ts: 2026-01-09T20:27:52.000+01:00, zone: Europe/Zurich, locale: en-US }
Error while creating CronJob CronError: WARNING: Date in past. Will never be fired.
    at CronTime.sendAt (/Users/kc/Code/ferropoly/ferropoly-main/node_modules/cron/dist/time.js:82:23)
    at CronTime.getTimeout (/Users/kc/Code/ferropoly/ferropoly-main/node_modules/cron/dist/time.js:100:21)
    at CronJob.start (/Users/kc/Code/ferropoly/ferropoly-main/node_modules/cron/dist/job.js:163:37)
    at new CronJob (/Users/kc/Code/ferropoly/ferropoly-main/node_modules/cron/dist/job.js:68:18)
    at CronJob.from (/Users/kc/Code/ferropoly/ferropoly-main/node_modules/cron/dist/job.js:81:20)
    at Object.<anonymous> (/Users/kc/Code/ferropoly/ferropoly-main/bin/cronTest.js:8:19)
    at Module._compile (node:internal/modules/cjs/loader:1738:14)
    at Object..js (node:internal/modules/cjs/loader:1871:10)
    at Module.load (node:internal/modules/cjs/loader:1470:32)
    at Module._load (node:internal/modules/cjs/loader:1290:12)

Process finished with exit code 0

```

It looks like the comparison in sendAt() does not care about a threshold.

Do I use / understand this function in a wrong way? How would I do better? Or can you confirm this as a bug (or missing feature, if you prefer)?
