### ISSUE TITLE
Something went wrong. cron reached maximum iterations

### ISSUE THREAD

**Issue by dikshamane** [kelektiv/node-cron#816]
We are got this error multiple times this week - here are 2  logs for ref :

Error: Something went wrong. cron reached maximum iterations.
Please open an  issue (https://github.com/kelektiv/node-cron/issues/new) and provide the following string
 Time Zone: "" - Cron String: 0 0,5,10,15,20,25,30,35,40,45,50,55 * * * * - UTC offset: +00:00 - current Date: Mon Dec 11 2023 15:05:49 GMT+0000

Error: Something went wrong. cron reached maximum iterations.
Please open an  issue (https://github.com/kelektiv/node-cron/issues/new) and provide the following string
Time Zone: "" - Cron String: 0 0,5,10,15,20,25,30,35,40,45,50,55 * * * * - UTC offset: +00:00 - current Date: Mon Dec 11 2023 15:05:49 GMT+0000
    at CronTime._getNextDateFrom (/usr/app/node_modules/cron/lib/cron.js:235:12)
    at CronTime.sendAt (/usr/app/node_modules/cron/lib/cron.js:156:17)
    at CronTime.getTimeout (/usr/app/node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (/usr/app/node_modules/cron/lib/cron.js:613:31)
    at Timeout.callbackWrapper [as _onTimeout] (/usr/app/node_modules/cron/lib/cron.js:665:29)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)

**Comment by sheerlox** [comment]
You're using a pretty old version of `cron`. Updating to at least the latest V2 version will fix this issue.
